<S>                 ::= <expr>
<expr>              ::= <expr> <op> <expr> 
                        ( <expr> )
                        <func> ( <expr> )
                        <digit>
                        <x>
<op>                ::= + | - | * | /
<func>              ::= math.sin | math.cos | math.exp | math.log
<digit>             ::= <digit><digit> | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0
<x>                 ::= x | -x
